name: 🕒 WakaTime Inline Stats

on:
  schedule:
    - cron: "15 5 * * *"  # Runs daily at 10:45 AM IST
  workflow_dispatch:

jobs:
  update-readme:
    name: 📊 Inject WakaTime Stats Inline
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@v0.2.8
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL: true
          SHOW_TITLE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_LANGUAGES: true
          COMMIT_MESSAGE: "📈 update waka stats"
