name: 🕒 WakaTime Dev Metrics

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12 PM IST
  workflow_dispatch:

jobs:
  update-readme:
    name: 📝 Update WakaTime Stats in README
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: ⚙️ Generate WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LINES_OF_CODE: false
          SHOW_LOC_CHART: false
