name: 🕒 WakaTime Inline Stats

on:
  schedule:
    - cron: "20 4 * * *"  # Runs daily at 9:50 AM IST (which is 4:20 AM UTC)
  workflow_dispatch:

jobs:
  update-readme:
    name: 📊 Inject WakaTime Stats Inline
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          COMMIT_MESSAGE: "📈 update waka stats"
