name: 🕒 WakaTime Inline Stats

on:
  schedule:
    - cron: "5 10 * * *"  # Runs daily at 1:00 PM IST (UTC+5:30)
  workflow_dispatch:

jobs:
  update-readme:
    name: 📊 Inject WakaTime Stats Inline
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@v0.3.1  # ✅ Latest stable version
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL: true
          SHOW_TITLE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_LANGUAGES: true
          COMMIT_MESSAGE: "📈 update waka stats"
